### ISSUE TITLE
Latest redmine_favorite_projects

### ISSUE THREAD

**Issue by kushlces** [AlphaNodes/redmine_favorite_projects#3]
Hi,
I love this idea of integration. Is there any chance that you will be integrating latest redmine_favorite_projects in this? Currently, in your plugin, I don't see options for Filters(except View Closed Projects)
Thanks
Kush

**Comment by alexandermeindl** [comment]
No, sorry. I created a fork and changed almost every line of the code. But if you send me an PR, I am willing to merge it.

**Comment by kushlces** [comment]
Ok. No worries. Thanks for the reply.
